export interface EmojiItem {
  name: string
  code: string
  url: string
}

export interface EmojiGroup {
  key: string
  name: string
  emojis: EmojiItem[]
}

// This file is generated from frontend/public/emojis/.
// Add/remove emoji image files there, then regenerate this config.
export const emojiGroups: EmojiGroup[] = [
    {
    key: 'tieba',
    name: '贴吧',
    emojis: [
      { name: '001', code: '[tieba:001]', url: '/emojis/tieba/tieba_001.png' },
      { name: '002', code: '[tieba:002]', url: '/emojis/tieba/tieba_002.png' },
      { name: '003', code: '[tieba:003]', url: '/emojis/tieba/tieba_003.png' },
      { name: '004', code: '[tieba:004]', url: '/emojis/tieba/tieba_004.png' },
      { name: '005', code: '[tieba:005]', url: '/emojis/tieba/tieba_005.png' },
      { name: '006', code: '[tieba:006]', url: '/emojis/tieba/tieba_006.png' },
      { name: '007', code: '[tieba:007]', url: '/emojis/tieba/tieba_007.png' },
      { name: '008', code: '[tieba:008]', url: '/emojis/tieba/tieba_008.png' },
      { name: '009', code: '[tieba:009]', url: '/emojis/tieba/tieba_009.png' },
      { name: '010', code: '[tieba:010]', url: '/emojis/tieba/tieba_010.png' },
      { name: '011', code: '[tieba:011]', url: '/emojis/tieba/tieba_011.png' },
      { name: '012', code: '[tieba:012]', url: '/emojis/tieba/tieba_012.png' },
      { name: '013', code: '[tieba:013]', url: '/emojis/tieba/tieba_013.png' },
      { name: '014', code: '[tieba:014]', url: '/emojis/tieba/tieba_014.png' },
      { name: '015', code: '[tieba:015]', url: '/emojis/tieba/tieba_015.png' },
      { name: '016', code: '[tieba:016]', url: '/emojis/tieba/tieba_016.png' },
      { name: '017', code: '[tieba:017]', url: '/emojis/tieba/tieba_017.png' },
      { name: '018', code: '[tieba:018]', url: '/emojis/tieba/tieba_018.png' },
      { name: '019', code: '[tieba:019]', url: '/emojis/tieba/tieba_019.png' },
      { name: '020', code: '[tieba:020]', url: '/emojis/tieba/tieba_020.png' },
      { name: '021', code: '[tieba:021]', url: '/emojis/tieba/tieba_021.png' },
      { name: '022', code: '[tieba:022]', url: '/emojis/tieba/tieba_022.png' },
      { name: '023', code: '[tieba:023]', url: '/emojis/tieba/tieba_023.png' },
      { name: '024', code: '[tieba:024]', url: '/emojis/tieba/tieba_024.png' },
      { name: '025', code: '[tieba:025]', url: '/emojis/tieba/tieba_025.png' },
      { name: '026', code: '[tieba:026]', url: '/emojis/tieba/tieba_026.png' },
      { name: '027', code: '[tieba:027]', url: '/emojis/tieba/tieba_027.png' },
      { name: '028', code: '[tieba:028]', url: '/emojis/tieba/tieba_028.png' },
      { name: '029', code: '[tieba:029]', url: '/emojis/tieba/tieba_029.png' },
      { name: '030', code: '[tieba:030]', url: '/emojis/tieba/tieba_030.png' },
      { name: '031', code: '[tieba:031]', url: '/emojis/tieba/tieba_031.png' },
      { name: '032', code: '[tieba:032]', url: '/emojis/tieba/tieba_032.png' },
      { name: '033', code: '[tieba:033]', url: '/emojis/tieba/tieba_033.png' },
      { name: '034', code: '[tieba:034]', url: '/emojis/tieba/tieba_034.png' },
      { name: '035', code: '[tieba:035]', url: '/emojis/tieba/tieba_035.png' },
      { name: '036', code: '[tieba:036]', url: '/emojis/tieba/tieba_036.png' },
      { name: '037', code: '[tieba:037]', url: '/emojis/tieba/tieba_037.png' },
      { name: '038', code: '[tieba:038]', url: '/emojis/tieba/tieba_038.png' },
      { name: '039', code: '[tieba:039]', url: '/emojis/tieba/tieba_039.png' },
      { name: '040', code: '[tieba:040]', url: '/emojis/tieba/tieba_040.png' },
      { name: '041', code: '[tieba:041]', url: '/emojis/tieba/tieba_041.png' },
      { name: '042', code: '[tieba:042]', url: '/emojis/tieba/tieba_042.png' },
      { name: '043', code: '[tieba:043]', url: '/emojis/tieba/tieba_043.png' },
      { name: '044', code: '[tieba:044]', url: '/emojis/tieba/tieba_044.png' },
      { name: '045', code: '[tieba:045]', url: '/emojis/tieba/tieba_045.png' },
      { name: '046', code: '[tieba:046]', url: '/emojis/tieba/tieba_046.png' },
      { name: '047', code: '[tieba:047]', url: '/emojis/tieba/tieba_047.png' },
      { name: '048', code: '[tieba:048]', url: '/emojis/tieba/tieba_048.png' },
      { name: '049', code: '[tieba:049]', url: '/emojis/tieba/tieba_049.png' },
      { name: '050', code: '[tieba:050]', url: '/emojis/tieba/tieba_050.png' },
      { name: '062', code: '[tieba:062]', url: '/emojis/tieba/tieba_062.png' },
      { name: '063', code: '[tieba:063]', url: '/emojis/tieba/tieba_063.png' },
      { name: '064', code: '[tieba:064]', url: '/emojis/tieba/tieba_064.png' },
      { name: '065', code: '[tieba:065]', url: '/emojis/tieba/tieba_065.png' },
      { name: '066', code: '[tieba:066]', url: '/emojis/tieba/tieba_066.png' },
      { name: '067', code: '[tieba:067]', url: '/emojis/tieba/tieba_067.png' },
      { name: '068', code: '[tieba:068]', url: '/emojis/tieba/tieba_068.png' },
      { name: '069', code: '[tieba:069]', url: '/emojis/tieba/tieba_069.png' },
      { name: '070', code: '[tieba:070]', url: '/emojis/tieba/tieba_070.png' },
      { name: '071', code: '[tieba:071]', url: '/emojis/tieba/tieba_071.png' },
      { name: '072', code: '[tieba:072]', url: '/emojis/tieba/tieba_072.png' },
      { name: '073', code: '[tieba:073]', url: '/emojis/tieba/tieba_073.png' },
      { name: '074', code: '[tieba:074]', url: '/emojis/tieba/tieba_074.png' },
      { name: '075', code: '[tieba:075]', url: '/emojis/tieba/tieba_075.png' },
      { name: '076', code: '[tieba:076]', url: '/emojis/tieba/tieba_076.png' },
      { name: '077', code: '[tieba:077]', url: '/emojis/tieba/tieba_077.png' },
      { name: '078', code: '[tieba:078]', url: '/emojis/tieba/tieba_078.png' },
      { name: '079', code: '[tieba:079]', url: '/emojis/tieba/tieba_079.png' },
      { name: '080', code: '[tieba:080]', url: '/emojis/tieba/tieba_080.png' },
      { name: '081', code: '[tieba:081]', url: '/emojis/tieba/tieba_081.png' },
      { name: '082', code: '[tieba:082]', url: '/emojis/tieba/tieba_082.png' },
      { name: '083', code: '[tieba:083]', url: '/emojis/tieba/tieba_083.png' },
      { name: '084', code: '[tieba:084]', url: '/emojis/tieba/tieba_084.png' },
      { name: '085', code: '[tieba:085]', url: '/emojis/tieba/tieba_085.png' },
      { name: '086', code: '[tieba:086]', url: '/emojis/tieba/tieba_086.png' },
      { name: '087', code: '[tieba:087]', url: '/emojis/tieba/tieba_087.png' },
      { name: '088', code: '[tieba:088]', url: '/emojis/tieba/tieba_088.png' },
      { name: '089', code: '[tieba:089]', url: '/emojis/tieba/tieba_089.png' },
      { name: '090', code: '[tieba:090]', url: '/emojis/tieba/tieba_090.png' },
      { name: '091', code: '[tieba:091]', url: '/emojis/tieba/tieba_091.png' },
      { name: '092', code: '[tieba:092]', url: '/emojis/tieba/tieba_092.png' },
      { name: '093', code: '[tieba:093]', url: '/emojis/tieba/tieba_093.png' },
      { name: '094', code: '[tieba:094]', url: '/emojis/tieba/tieba_094.png' },
      { name: '095', code: '[tieba:095]', url: '/emojis/tieba/tieba_095.png' },
      { name: '096', code: '[tieba:096]', url: '/emojis/tieba/tieba_096.png' },
      { name: '097', code: '[tieba:097]', url: '/emojis/tieba/tieba_097.png' },
      { name: '098', code: '[tieba:098]', url: '/emojis/tieba/tieba_098.png' },
      { name: '099', code: '[tieba:099]', url: '/emojis/tieba/tieba_099.png' },
      { name: '100', code: '[tieba:100]', url: '/emojis/tieba/tieba_100.png' },
      { name: '101', code: '[tieba:101]', url: '/emojis/tieba/tieba_101.png' },
      { name: '102', code: '[tieba:102]', url: '/emojis/tieba/tieba_102.png' },
      { name: '103', code: '[tieba:103]', url: '/emojis/tieba/tieba_103.png' },
      { name: '104', code: '[tieba:104]', url: '/emojis/tieba/tieba_104.png' },
      { name: '105', code: '[tieba:105]', url: '/emojis/tieba/tieba_105.png' },
      { name: '106', code: '[tieba:106]', url: '/emojis/tieba/tieba_106.png' },
      { name: '107', code: '[tieba:107]', url: '/emojis/tieba/tieba_107.png' },
      { name: '108', code: '[tieba:108]', url: '/emojis/tieba/tieba_108.png' },
      { name: '109', code: '[tieba:109]', url: '/emojis/tieba/tieba_109.png' },
      { name: '110', code: '[tieba:110]', url: '/emojis/tieba/tieba_110.png' },
      { name: '111', code: '[tieba:111]', url: '/emojis/tieba/tieba_111.png' },
      { name: '112', code: '[tieba:112]', url: '/emojis/tieba/tieba_112.png' },
      { name: '113', code: '[tieba:113]', url: '/emojis/tieba/tieba_113.png' },
      { name: '114', code: '[tieba:114]', url: '/emojis/tieba/tieba_114.png' },
      { name: '115', code: '[tieba:115]', url: '/emojis/tieba/tieba_115.png' },
      { name: '116', code: '[tieba:116]', url: '/emojis/tieba/tieba_116.png' },
      { name: '117', code: '[tieba:117]', url: '/emojis/tieba/tieba_117.png' },
      { name: '118', code: '[tieba:118]', url: '/emojis/tieba/tieba_118.png' },
      { name: '119', code: '[tieba:119]', url: '/emojis/tieba/tieba_119.png' },
      { name: '120', code: '[tieba:120]', url: '/emojis/tieba/tieba_120.png' },
      { name: '121', code: '[tieba:121]', url: '/emojis/tieba/tieba_121.png' },
      { name: '122', code: '[tieba:122]', url: '/emojis/tieba/tieba_122.png' },
      { name: '123', code: '[tieba:123]', url: '/emojis/tieba/tieba_123.png' },
      { name: '124', code: '[tieba:124]', url: '/emojis/tieba/tieba_124.png' },
    ]
  },
  {
    key: 'bilibili',
    name: '哔站',
    emojis: [
      { name: 'FGO_偷看', code: '[bilibili:FGO_偷看]', url: '/emojis/bilibili/bili_FGO_偷看.png' },
      { name: 'FGO_开心', code: '[bilibili:FGO_开心]', url: '/emojis/bilibili/bili_FGO_开心.png' },
      { name: 'FGO_怒', code: '[bilibili:FGO_怒]', url: '/emojis/bilibili/bili_FGO_怒.png' },
      { name: 'FGO_汗', code: '[bilibili:FGO_汗]', url: '/emojis/bilibili/bili_FGO_汗.png' },
      { name: 'FGO_耶', code: '[bilibili:FGO_耶]', url: '/emojis/bilibili/bili_FGO_耶.png' },
      { name: 'OK', code: '[bilibili:OK]', url: '/emojis/bilibili/bili_OK.png' },
      { name: 'doge', code: '[bilibili:doge]', url: '/emojis/bilibili/bili_doge.png' },
      { name: 'doge_金箍', code: '[bilibili:doge_金箍]', url: '/emojis/bilibili/bili_doge_金箍.png' },
      { name: 'tv_小电视', code: '[bilibili:tv_小电视]', url: '/emojis/bilibili/bili_tv_小电视.png' },
      { name: '三星堆', code: '[bilibili:三星堆]', url: '/emojis/bilibili/bili_三星堆.png' },
      { name: '以闪亮之名_吃瓜', code: '[bilibili:以闪亮之名_吃瓜]', url: '/emojis/bilibili/bili_以闪亮之名_吃瓜.png' },
      { name: '以闪亮之名_哎？！', code: '[bilibili:以闪亮之名_哎？！]', url: '/emojis/bilibili/bili_以闪亮之名_哎？！.png' },
      { name: '以闪亮之名_好耶!', code: '[bilibili:以闪亮之名_好耶!]', url: '/emojis/bilibili/bili_以闪亮之名_好耶!.png' },
      { name: '以闪亮之名_星星眼', code: '[bilibili:以闪亮之名_星星眼]', url: '/emojis/bilibili/bili_以闪亮之名_星星眼.png' },
      { name: '以闪亮之名_爱你哦', code: '[bilibili:以闪亮之名_爱你哦]', url: '/emojis/bilibili/bili_以闪亮之名_爱你哦.png' },
      { name: '以闪亮之名_针不戳', code: '[bilibili:以闪亮之名_针不戳]', url: '/emojis/bilibili/bili_以闪亮之名_针不戳.png' },
      { name: '保佑', code: '[bilibili:保佑]', url: '/emojis/bilibili/bili_保佑.png' },
      { name: '保卫萝卜_哇', code: '[bilibili:保卫萝卜_哇]', url: '/emojis/bilibili/bili_保卫萝卜_哇.png' },
      { name: '保卫萝卜_哭哭', code: '[bilibili:保卫萝卜_哭哭]', url: '/emojis/bilibili/bili_保卫萝卜_哭哭.png' },
      { name: '保卫萝卜_白眼', code: '[bilibili:保卫萝卜_白眼]', url: '/emojis/bilibili/bili_保卫萝卜_白眼.png' },
      { name: '保卫萝卜_笔芯', code: '[bilibili:保卫萝卜_笔芯]', url: '/emojis/bilibili/bili_保卫萝卜_笔芯.png' },
      { name: '保卫萝卜_问号', code: '[bilibili:保卫萝卜_问号]', url: '/emojis/bilibili/bili_保卫萝卜_问号.png' },
      { name: '偷笑', code: '[bilibili:偷笑]', url: '/emojis/bilibili/bili_偷笑.png' },
      { name: '傲娇', code: '[bilibili:傲娇]', url: '/emojis/bilibili/bili_傲娇.png' },
      { name: '元梦_哭哭', code: '[bilibili:元梦_哭哭]', url: '/emojis/bilibili/bili_元梦_哭哭.png' },
      { name: '元梦_大哭', code: '[bilibili:元梦_大哭]', url: '/emojis/bilibili/bili_元梦_大哭.png' },
      { name: '元梦_打call', code: '[bilibili:元梦_打call]', url: '/emojis/bilibili/bili_元梦_打call.png' },
      { name: '元梦_点赞', code: '[bilibili:元梦_点赞]', url: '/emojis/bilibili/bili_元梦_点赞.png' },
      { name: '元梦_爱你', code: '[bilibili:元梦_爱你]', url: '/emojis/bilibili/bili_元梦_爱你.png' },
      { name: '兔兔岛_吃面', code: '[bilibili:兔兔岛_吃面]', url: '/emojis/bilibili/bili_兔兔岛_吃面.png' },
      { name: '兔兔岛_开心', code: '[bilibili:兔兔岛_开心]', url: '/emojis/bilibili/bili_兔兔岛_开心.png' },
      { name: '兔兔岛_睡觉', code: '[bilibili:兔兔岛_睡觉]', url: '/emojis/bilibili/bili_兔兔岛_睡觉.png' },
      { name: '兔年', code: '[bilibili:兔年]', url: '/emojis/bilibili/bili_兔年.png' },
      { name: '再见', code: '[bilibili:再见]', url: '/emojis/bilibili/bili_再见.png' },
      { name: '冷', code: '[bilibili:冷]', url: '/emojis/bilibili/bili_冷.png' },
      { name: '初音未来_大笑', code: '[bilibili:初音未来_大笑]', url: '/emojis/bilibili/bili_初音未来_大笑.png' },
      { name: '加油', code: '[bilibili:加油]', url: '/emojis/bilibili/bili_加油.png' },
      { name: '原神_哇', code: '[bilibili:原神_哇]', url: '/emojis/bilibili/bili_原神_哇.png' },
      { name: '原神_哼', code: '[bilibili:原神_哼]', url: '/emojis/bilibili/bili_原神_哼.png' },
      { name: '原神_喝茶', code: '[bilibili:原神_喝茶]', url: '/emojis/bilibili/bili_原神_喝茶.png' },
      { name: '原神_嗯', code: '[bilibili:原神_嗯]', url: '/emojis/bilibili/bili_原神_嗯.png' },
      { name: '原神_欸嘿', code: '[bilibili:原神_欸嘿]', url: '/emojis/bilibili/bili_原神_欸嘿.png' },
      { name: '原神_生气', code: '[bilibili:原神_生气]', url: '/emojis/bilibili/bili_原神_生气.png' },
      { name: '口罩', code: '[bilibili:口罩]', url: '/emojis/bilibili/bili_口罩.png' },
      { name: '吃瓜', code: '[bilibili:吃瓜]', url: '/emojis/bilibili/bili_吃瓜.png' },
      { name: '呆', code: '[bilibili:呆]', url: '/emojis/bilibili/bili_呆.png' },
      { name: '呲牙', code: '[bilibili:呲牙]', url: '/emojis/bilibili/bili_呲牙.png' },
      { name: '哈欠', code: '[bilibili:哈欠]', url: '/emojis/bilibili/bili_哈欠.png' },
      { name: '响指', code: '[bilibili:响指]', url: '/emojis/bilibili/bili_响指.png' },
      { name: '哦呼', code: '[bilibili:哦呼]', url: '/emojis/bilibili/bili_哦呼.png' },
      { name: '喜极而泣', code: '[bilibili:喜极而泣]', url: '/emojis/bilibili/bili_喜极而泣.png' },
      { name: '喜欢', code: '[bilibili:喜欢]', url: '/emojis/bilibili/bili_喜欢.png' },
      { name: '嗑瓜子', code: '[bilibili:嗑瓜子]', url: '/emojis/bilibili/bili_嗑瓜子.png' },
      { name: '嘘声', code: '[bilibili:嘘声]', url: '/emojis/bilibili/bili_嘘声.png' },
      { name: '嘟嘟', code: '[bilibili:嘟嘟]', url: '/emojis/bilibili/bili_嘟嘟.png' },
      { name: '坂本_佛系', code: '[bilibili:坂本_佛系]', url: '/emojis/bilibili/bili_坂本_佛系.png' },
      { name: '坎公骑冠剑_吃鸡', code: '[bilibili:坎公骑冠剑_吃鸡]', url: '/emojis/bilibili/bili_坎公骑冠剑_吃鸡.png' },
      { name: '坎公骑冠剑_无语', code: '[bilibili:坎公骑冠剑_无语]', url: '/emojis/bilibili/bili_坎公骑冠剑_无语.png' },
      { name: '坎公骑冠剑_钻石', code: '[bilibili:坎公骑冠剑_钻石]', url: '/emojis/bilibili/bili_坎公骑冠剑_钻石.png' },
      { name: '墨镜', code: '[bilibili:墨镜]', url: '/emojis/bilibili/bili_墨镜.png' },
      { name: '大哭', code: '[bilibili:大哭]', url: '/emojis/bilibili/bili_大哭.png' },
      { name: '大笑', code: '[bilibili:大笑]', url: '/emojis/bilibili/bili_大笑.png' },
      { name: '奋斗', code: '[bilibili:奋斗]', url: '/emojis/bilibili/bili_奋斗.png' },
      { name: '奥比岛_击爪', code: '[bilibili:奥比岛_击爪]', url: '/emojis/bilibili/bili_奥比岛_击爪.png' },
      { name: '奥比岛_喜欢', code: '[bilibili:奥比岛_喜欢]', url: '/emojis/bilibili/bili_奥比岛_喜欢.png' },
      { name: '奥比岛_委屈', code: '[bilibili:奥比岛_委屈]', url: '/emojis/bilibili/bili_奥比岛_委屈.png' },
      { name: '奥比岛_搬砖', code: '[bilibili:奥比岛_搬砖]', url: '/emojis/bilibili/bili_奥比岛_搬砖.png' },
      { name: '奥比岛_点赞', code: '[bilibili:奥比岛_点赞]', url: '/emojis/bilibili/bili_奥比岛_点赞.png' },
      { name: '奶茶干杯', code: '[bilibili:奶茶干杯]', url: '/emojis/bilibili/bili_奶茶干杯.png' },
      { name: '妙啊', code: '[bilibili:妙啊]', url: '/emojis/bilibili/bili_妙啊.png' },
      { name: '委屈', code: '[bilibili:委屈]', url: '/emojis/bilibili/bili_委屈.png' },
      { name: '嫌弃', code: '[bilibili:嫌弃]', url: '/emojis/bilibili/bili_嫌弃.png' },
      { name: '害羞', code: '[bilibili:害羞]', url: '/emojis/bilibili/bili_害羞.png' },
      { name: '小黄脸', code: '[bilibili:小黄脸]', url: '/emojis/bilibili/bili_小黄脸.png' },
      { name: '少女乐团派对_开心', code: '[bilibili:少女乐团派对_开心]', url: '/emojis/bilibili/bili_少女乐团派对_开心.png' },
      { name: '少女乐团派对_感想', code: '[bilibili:少女乐团派对_感想]', url: '/emojis/bilibili/bili_少女乐团派对_感想.png' },
      { name: '少女乐团派对_期待', code: '[bilibili:少女乐团派对_期待]', url: '/emojis/bilibili/bili_少女乐团派对_期待.png' },
      { name: '少女乐团派对_派对', code: '[bilibili:少女乐团派对_派对]', url: '/emojis/bilibili/bili_少女乐团派对_派对.png' },
      { name: '少女乐团派对_等一下', code: '[bilibili:少女乐团派对_等一下]', url: '/emojis/bilibili/bili_少女乐团派对_等一下.png' },
      { name: '尴尬', code: '[bilibili:尴尬]', url: '/emojis/bilibili/bili_尴尬.png' },
      { name: '干杯', code: '[bilibili:干杯]', url: '/emojis/bilibili/bili_干杯.png' },
      { name: '微笑', code: '[bilibili:微笑]', url: '/emojis/bilibili/bili_微笑.png' },
      { name: '思考', code: '[bilibili:思考]', url: '/emojis/bilibili/bili_思考.png' },
      { name: '怪兽8号_开心', code: '[bilibili:怪兽8号_开心]', url: '/emojis/bilibili/bili_怪兽8号_开心.png' },
      { name: '怪我咯', code: '[bilibili:怪我咯]', url: '/emojis/bilibili/bili_怪我咯.png' },
      { name: '惊喜', code: '[bilibili:惊喜]', url: '/emojis/bilibili/bili_惊喜.png' },
      { name: '惊讶', code: '[bilibili:惊讶]', url: '/emojis/bilibili/bili_惊讶.png' },
      { name: '我独自升级_疑惑', code: '[bilibili:我独自升级_疑惑]', url: '/emojis/bilibili/bili_我独自升级_疑惑.png' },
      { name: '打call', code: '[bilibili:打call]', url: '/emojis/bilibili/bili_打call.png' },
      { name: '抓狂', code: '[bilibili:抓狂]', url: '/emojis/bilibili/bili_抓狂.png' },
      { name: '抠鼻', code: '[bilibili:抠鼻]', url: '/emojis/bilibili/bili_抠鼻.png' },
      { name: '抱拳', code: '[bilibili:抱拳]', url: '/emojis/bilibili/bili_抱拳.png' },
      { name: '拥抱', code: '[bilibili:拥抱]', url: '/emojis/bilibili/bili_拥抱.png' },
      { name: '捂眼', code: '[bilibili:捂眼]', url: '/emojis/bilibili/bili_捂眼.png' },
      { name: '捂脸', code: '[bilibili:捂脸]', url: '/emojis/bilibili/bili_捂脸.png' },
      { name: '撇嘴', code: '[bilibili:撇嘴]', url: '/emojis/bilibili/bili_撇嘴.png' },
      { name: '支持', code: '[bilibili:支持]', url: '/emojis/bilibili/bili_支持.png' },
      { name: '无悔华夏_不愧是你', code: '[bilibili:无悔华夏_不愧是你]', url: '/emojis/bilibili/bili_无悔华夏_不愧是你.png' },
      { name: '无悔华夏_吃瓜', code: '[bilibili:无悔华夏_吃瓜]', url: '/emojis/bilibili/bili_无悔华夏_吃瓜.png' },
      { name: '无悔华夏_好耶', code: '[bilibili:无悔华夏_好耶]', url: '/emojis/bilibili/bili_无悔华夏_好耶.png' },
      { name: '无悔华夏_点赞', code: '[bilibili:无悔华夏_点赞]', url: '/emojis/bilibili/bili_无悔华夏_点赞.png' },
      { name: '无悔华夏_达咩', code: '[bilibili:无悔华夏_达咩]', url: '/emojis/bilibili/bili_无悔华夏_达咩.png' },
      { name: '无语', code: '[bilibili:无语]', url: '/emojis/bilibili/bili_无语.png' },
      { name: '无限暖暖_单品灵', code: '[bilibili:无限暖暖_单品灵]', url: '/emojis/bilibili/bili_无限暖暖_单品灵.png' },
      { name: '无限暖暖_围兜狸猫', code: '[bilibili:无限暖暖_围兜狸猫]', url: '/emojis/bilibili/bili_无限暖暖_围兜狸猫.png' },
      { name: '无限暖暖_大喵', code: '[bilibili:无限暖暖_大喵]', url: '/emojis/bilibili/bili_无限暖暖_大喵.png' },
      { name: '无限暖暖_心愿精灵', code: '[bilibili:无限暖暖_心愿精灵]', url: '/emojis/bilibili/bili_无限暖暖_心愿精灵.png' },
      { name: '无限暖暖_暖暖', code: '[bilibili:无限暖暖_暖暖]', url: '/emojis/bilibili/bili_无限暖暖_暖暖.png' },
      { name: '无限暖暖_毛线汪汪', code: '[bilibili:无限暖暖_毛线汪汪]', url: '/emojis/bilibili/bili_无限暖暖_毛线汪汪.png' },
      { name: '无限暖暖_美食家蜜蜂', code: '[bilibili:无限暖暖_美食家蜜蜂]', url: '/emojis/bilibili/bili_无限暖暖_美食家蜜蜂.png' },
      { name: '无限暖暖_袜袜羊', code: '[bilibili:无限暖暖_袜袜羊]', url: '/emojis/bilibili/bili_无限暖暖_袜袜羊.png' },
      { name: '星星眼', code: '[bilibili:星星眼]', url: '/emojis/bilibili/bili_星星眼.png' },
      { name: '来古-呆滞', code: '[bilibili:来古-呆滞]', url: '/emojis/bilibili/bili_来古-呆滞.png' },
      { name: '来古-沉思', code: '[bilibili:来古-沉思]', url: '/emojis/bilibili/bili_来古-沉思.png' },
      { name: '来古-注意', code: '[bilibili:来古-注意]', url: '/emojis/bilibili/bili_来古-注意.png' },
      { name: '来古-疑问', code: '[bilibili:来古-疑问]', url: '/emojis/bilibili/bili_来古-疑问.png' },
      { name: '来古-震撼', code: '[bilibili:来古-震撼]', url: '/emojis/bilibili/bili_来古-震撼.png' },
      { name: '桃源_乖巧', code: '[bilibili:桃源_乖巧]', url: '/emojis/bilibili/bili_桃源_乖巧.png' },
      { name: '桃源_傲娇', code: '[bilibili:桃源_傲娇]', url: '/emojis/bilibili/bili_桃源_傲娇.png' },
      { name: '桃源_欢呼', code: '[bilibili:桃源_欢呼]', url: '/emojis/bilibili/bili_桃源_欢呼.png' },
      { name: '桃源_给花花', code: '[bilibili:桃源_给花花]', url: '/emojis/bilibili/bili_桃源_给花花.png' },
      { name: '桃源_缘分', code: '[bilibili:桃源_缘分]', url: '/emojis/bilibili/bili_桃源_缘分.png' },
      { name: '歪嘴', code: '[bilibili:歪嘴]', url: '/emojis/bilibili/bili_歪嘴.png' },
      { name: '水稻', code: '[bilibili:水稻]', url: '/emojis/bilibili/bili_水稻.png' },
      { name: '汤圆', code: '[bilibili:汤圆]', url: '/emojis/bilibili/bili_汤圆.png' },
      { name: '洛天依', code: '[bilibili:洛天依]', url: '/emojis/bilibili/bili_洛天依.png' },
      { name: '滑稽', code: '[bilibili:滑稽]', url: '/emojis/bilibili/bili_滑稽.png' },
      { name: '灵魂出窍', code: '[bilibili:灵魂出窍]', url: '/emojis/bilibili/bili_灵魂出窍.png' },
      { name: '点赞', code: '[bilibili:点赞]', url: '/emojis/bilibili/bili_点赞.png' },
      { name: '热', code: '[bilibili:热]', url: '/emojis/bilibili/bili_热.png' },
      { name: '热词系列一', code: '[bilibili:热词系列一]', url: '/emojis/bilibili/bili_热词系列一.png' },
      { name: '爱心', code: '[bilibili:爱心]', url: '/emojis/bilibili/bili_爱心.png' },
      { name: '牛年', code: '[bilibili:牛年]', url: '/emojis/bilibili/bili_牛年.png' },
      { name: '猴哥', code: '[bilibili:猴哥]', url: '/emojis/bilibili/bili_猴哥.png' },
      { name: '生气', code: '[bilibili:生气]', url: '/emojis/bilibili/bili_生气.png' },
      { name: '生气_金箍', code: '[bilibili:生气_金箍]', url: '/emojis/bilibili/bili_生气_金箍.png' },
      { name: '生病', code: '[bilibili:生病]', url: '/emojis/bilibili/bili_生病.png' },
      { name: '疑惑', code: '[bilibili:疑惑]', url: '/emojis/bilibili/bili_疑惑.png' },
      { name: '疼', code: '[bilibili:疼]', url: '/emojis/bilibili/bili_疼.png' },
      { name: '白荆回廊_啊？', code: '[bilibili:白荆回廊_啊？]', url: '/emojis/bilibili/bili_白荆回廊_啊？.png' },
      { name: '白荆回廊_好好好', code: '[bilibili:白荆回廊_好好好]', url: '/emojis/bilibili/bili_白荆回廊_好好好.png' },
      { name: '白荆回廊_尴尬', code: '[bilibili:白荆回廊_尴尬]', url: '/emojis/bilibili/bili_白荆回廊_尴尬.png' },
      { name: '白荆回廊_无语', code: '[bilibili:白荆回廊_无语]', url: '/emojis/bilibili/bili_白荆回廊_无语.png' },
      { name: '白荆回廊_期待', code: '[bilibili:白荆回廊_期待]', url: '/emojis/bilibili/bili_白荆回廊_期待.png' },
      { name: '白荆回廊_欢呼', code: '[bilibili:白荆回廊_欢呼]', url: '/emojis/bilibili/bili_白荆回廊_欢呼.png' },
      { name: '福', code: '[bilibili:福]', url: '/emojis/bilibili/bili_福.png' },
      { name: '福到了', code: '[bilibili:福到了]', url: '/emojis/bilibili/bili_福到了.png' },
      { name: '笑', code: '[bilibili:笑]', url: '/emojis/bilibili/bili_笑.png' },
      { name: '笑哭', code: '[bilibili:笑哭]', url: '/emojis/bilibili/bili_笑哭.png' },
      { name: '给心心', code: '[bilibili:给心心]', url: '/emojis/bilibili/bili_给心心.png' },
      { name: '翻白眼', code: '[bilibili:翻白眼]', url: '/emojis/bilibili/bili_翻白眼.png' },
      { name: '老鼠', code: '[bilibili:老鼠]', url: '/emojis/bilibili/bili_老鼠.png' },
      { name: '胆大党_微笑', code: '[bilibili:胆大党_微笑]', url: '/emojis/bilibili/bili_胆大党_微笑.png' },
      { name: '胜利', code: '[bilibili:胜利]', url: '/emojis/bilibili/bili_胜利.png' },
      { name: '脱单doge', code: '[bilibili:脱单doge]', url: '/emojis/bilibili/bili_脱单doge.png' },
      { name: '脸红', code: '[bilibili:脸红]', url: '/emojis/bilibili/bili_脸红.png' },
      { name: '藏狐', code: '[bilibili:藏狐]', url: '/emojis/bilibili/bili_藏狐.png' },
      { name: '视频卫星', code: '[bilibili:视频卫星]', url: '/emojis/bilibili/bili_视频卫星.png' },
      { name: '调皮', code: '[bilibili:调皮]', url: '/emojis/bilibili/bili_调皮.png' },
      { name: '豹富', code: '[bilibili:豹富]', url: '/emojis/bilibili/bili_豹富.png' },
      { name: '跪了', code: '[bilibili:跪了]', url: '/emojis/bilibili/bili_跪了.png' },
      { name: '蹲蹲', code: '[bilibili:蹲蹲]', url: '/emojis/bilibili/bili_蹲蹲.png' },
      { name: '辣眼睛', code: '[bilibili:辣眼睛]', url: '/emojis/bilibili/bili_辣眼睛.png' },
      { name: '酸了', code: '[bilibili:酸了]', url: '/emojis/bilibili/bili_酸了.png' },
      { name: '重返未来1999_什么', code: '[bilibili:重返未来1999_什么]', url: '/emojis/bilibili/bili_重返未来1999_什么.png' },
      { name: '重返未来1999_喂', code: '[bilibili:重返未来1999_喂]', url: '/emojis/bilibili/bili_重返未来1999_喂.png' },
      { name: '重返未来1999_谢谢老板', code: '[bilibili:重返未来1999_谢谢老板]', url: '/emojis/bilibili/bili_重返未来1999_谢谢老板.png' },
      { name: '重返未来1999_赞', code: '[bilibili:重返未来1999_赞]', url: '/emojis/bilibili/bili_重返未来1999_赞.png' },
      { name: '锦鲤', code: '[bilibili:锦鲤]', url: '/emojis/bilibili/bili_锦鲤.png' },
      { name: '阴险', code: '[bilibili:阴险]', url: '/emojis/bilibili/bili_阴险.png' },
      { name: '难过', code: '[bilibili:难过]', url: '/emojis/bilibili/bili_难过.png' },
      { name: '雪花', code: '[bilibili:雪花]', url: '/emojis/bilibili/bili_雪花.png' },
      { name: '颂乐人偶_眯眼笑', code: '[bilibili:颂乐人偶_眯眼笑]', url: '/emojis/bilibili/bili_颂乐人偶_眯眼笑.png' },
      { name: '颜文字', code: '[bilibili:颜文字]', url: '/emojis/bilibili/bili_颜文字.png' },
      { name: '香格里拉边境', code: '[bilibili:香格里拉边境]', url: '/emojis/bilibili/bili_香格里拉边境.png' },
      { name: '鸡腿', code: '[bilibili:鸡腿]', url: '/emojis/bilibili/bili_鸡腿.png' },
      { name: '鸣潮_你好', code: '[bilibili:鸣潮_你好]', url: '/emojis/bilibili/bili_鸣潮_你好.png' },
      { name: '鸣潮_咦', code: '[bilibili:鸣潮_咦]', url: '/emojis/bilibili/bili_鸣潮_咦.png' },
      { name: '鸣潮_哇', code: '[bilibili:鸣潮_哇]', url: '/emojis/bilibili/bili_鸣潮_哇.png' },
      { name: '鸣潮_唉', code: '[bilibili:鸣潮_唉]', url: '/emojis/bilibili/bili_鸣潮_唉.png' },
      { name: '鸣潮_嗨', code: '[bilibili:鸣潮_嗨]', url: '/emojis/bilibili/bili_鸣潮_嗨.png' },
      { name: '鸣潮_嗯', code: '[bilibili:鸣潮_嗯]', url: '/emojis/bilibili/bili_鸣潮_嗯.png' },
      { name: '鸣潮_嘿', code: '[bilibili:鸣潮_嘿]', url: '/emojis/bilibili/bili_鸣潮_嘿.png' },
      { name: '鸣潮_嘿嘿', code: '[bilibili:鸣潮_嘿嘿]', url: '/emojis/bilibili/bili_鸣潮_嘿嘿.png' },
      { name: '鸣潮_好呀', code: '[bilibili:鸣潮_好呀]', url: '/emojis/bilibili/bili_鸣潮_好呀.png' },
      { name: '鸣潮_祈愿', code: '[bilibili:鸣潮_祈愿]', url: '/emojis/bilibili/bili_鸣潮_祈愿.png' },
      { name: '黎明觉醒_哼白眼鸦', code: '[bilibili:黎明觉醒_哼白眼鸦]', url: '/emojis/bilibili/bili_黎明觉醒_哼白眼鸦.png' },
      { name: '黎明觉醒_怒了鸦', code: '[bilibili:黎明觉醒_怒了鸦]', url: '/emojis/bilibili/bili_黎明觉醒_怒了鸦.png' },
      { name: '黎明觉醒_摊手鸦', code: '[bilibili:黎明觉醒_摊手鸦]', url: '/emojis/bilibili/bili_黎明觉醒_摊手鸦.png' },
      { name: '黎明觉醒_比心鸦', code: '[bilibili:黎明觉醒_比心鸦]', url: '/emojis/bilibili/bili_黎明觉醒_比心鸦.png' },
      { name: '黎明觉醒_石化鸦', code: '[bilibili:黎明觉醒_石化鸦]', url: '/emojis/bilibili/bili_黎明觉醒_石化鸦.png' },
      { name: '黑洞', code: '[bilibili:黑洞]', url: '/emojis/bilibili/bili_黑洞.png' },
      { name: '黑眼圈_金箍', code: '[bilibili:黑眼圈_金箍]', url: '/emojis/bilibili/bili_黑眼圈_金箍.png' },
      { name: '鼓掌', code: '[bilibili:鼓掌]', url: '/emojis/bilibili/bili_鼓掌.png' },
      { name: '龙年', code: '[bilibili:龙年]', url: '/emojis/bilibili/bili_龙年.png' },
    ]
  },
  {
    key: 'lark',
    name: '飞书',
    emojis: [
      { name: '001', code: '[lark:001]', url: '/emojis/lark/lark_001.png' },
      { name: '002', code: '[lark:002]', url: '/emojis/lark/lark_002.png' },
      { name: '003', code: '[lark:003]', url: '/emojis/lark/lark_003.png' },
      { name: '004', code: '[lark:004]', url: '/emojis/lark/lark_004.png' },
      { name: '005', code: '[lark:005]', url: '/emojis/lark/lark_005.png' },
      { name: '006', code: '[lark:006]', url: '/emojis/lark/lark_006.png' },
      { name: '007', code: '[lark:007]', url: '/emojis/lark/lark_007.png' },
      { name: '008', code: '[lark:008]', url: '/emojis/lark/lark_008.png' },
      { name: '009', code: '[lark:009]', url: '/emojis/lark/lark_009.png' },
      { name: '010', code: '[lark:010]', url: '/emojis/lark/lark_010.png' },
      { name: '011', code: '[lark:011]', url: '/emojis/lark/lark_011.png' },
      { name: '012', code: '[lark:012]', url: '/emojis/lark/lark_012.png' },
      { name: '013', code: '[lark:013]', url: '/emojis/lark/lark_013.png' },
      { name: '014', code: '[lark:014]', url: '/emojis/lark/lark_014.png' },
      { name: '015', code: '[lark:015]', url: '/emojis/lark/lark_015.png' },
      { name: '016', code: '[lark:016]', url: '/emojis/lark/lark_016.png' },
      { name: '017', code: '[lark:017]', url: '/emojis/lark/lark_017.png' },
      { name: '018', code: '[lark:018]', url: '/emojis/lark/lark_018.png' },
      { name: '019', code: '[lark:019]', url: '/emojis/lark/lark_019.png' },
      { name: '020', code: '[lark:020]', url: '/emojis/lark/lark_020.png' },
      { name: '021', code: '[lark:021]', url: '/emojis/lark/lark_021.png' },
      { name: '022', code: '[lark:022]', url: '/emojis/lark/lark_022.png' },
      { name: '023', code: '[lark:023]', url: '/emojis/lark/lark_023.png' },
      { name: '024', code: '[lark:024]', url: '/emojis/lark/lark_024.png' },
      { name: '025', code: '[lark:025]', url: '/emojis/lark/lark_025.png' },
      { name: '026', code: '[lark:026]', url: '/emojis/lark/lark_026.png' },
      { name: '027', code: '[lark:027]', url: '/emojis/lark/lark_027.png' },
      { name: '028', code: '[lark:028]', url: '/emojis/lark/lark_028.png' },
      { name: '029', code: '[lark:029]', url: '/emojis/lark/lark_029.png' },
      { name: '030', code: '[lark:030]', url: '/emojis/lark/lark_030.png' },
      { name: '031', code: '[lark:031]', url: '/emojis/lark/lark_031.png' },
      { name: '032', code: '[lark:032]', url: '/emojis/lark/lark_032.png' },
      { name: '033', code: '[lark:033]', url: '/emojis/lark/lark_033.png' },
      { name: '034', code: '[lark:034]', url: '/emojis/lark/lark_034.png' },
      { name: '035', code: '[lark:035]', url: '/emojis/lark/lark_035.png' },
      { name: '036', code: '[lark:036]', url: '/emojis/lark/lark_036.png' },
      { name: '037', code: '[lark:037]', url: '/emojis/lark/lark_037.png' },
      { name: '038', code: '[lark:038]', url: '/emojis/lark/lark_038.png' },
      { name: '039', code: '[lark:039]', url: '/emojis/lark/lark_039.png' },
      { name: '040', code: '[lark:040]', url: '/emojis/lark/lark_040.png' },
      { name: '041', code: '[lark:041]', url: '/emojis/lark/lark_041.png' },
      { name: '042', code: '[lark:042]', url: '/emojis/lark/lark_042.png' },
      { name: '043', code: '[lark:043]', url: '/emojis/lark/lark_043.png' },
      { name: '044', code: '[lark:044]', url: '/emojis/lark/lark_044.png' },
      { name: '045', code: '[lark:045]', url: '/emojis/lark/lark_045.png' },
      { name: '046', code: '[lark:046]', url: '/emojis/lark/lark_046.png' },
      { name: '047', code: '[lark:047]', url: '/emojis/lark/lark_047.png' },
      { name: '048', code: '[lark:048]', url: '/emojis/lark/lark_048.png' },
      { name: '049', code: '[lark:049]', url: '/emojis/lark/lark_049.png' },
      { name: '050', code: '[lark:050]', url: '/emojis/lark/lark_050.png' },
      { name: '051', code: '[lark:051]', url: '/emojis/lark/lark_051.png' },
      { name: '052', code: '[lark:052]', url: '/emojis/lark/lark_052.png' },
      { name: '053', code: '[lark:053]', url: '/emojis/lark/lark_053.png' },
      { name: '054', code: '[lark:054]', url: '/emojis/lark/lark_054.png' },
      { name: '055', code: '[lark:055]', url: '/emojis/lark/lark_055.png' },
      { name: '056', code: '[lark:056]', url: '/emojis/lark/lark_056.png' },
      { name: '057', code: '[lark:057]', url: '/emojis/lark/lark_057.png' },
      { name: '058', code: '[lark:058]', url: '/emojis/lark/lark_058.png' },
      { name: '059', code: '[lark:059]', url: '/emojis/lark/lark_059.png' },
      { name: '060', code: '[lark:060]', url: '/emojis/lark/lark_060.png' },
      { name: '061', code: '[lark:061]', url: '/emojis/lark/lark_061.png' },
      { name: '062', code: '[lark:062]', url: '/emojis/lark/lark_062.png' },
      { name: '063', code: '[lark:063]', url: '/emojis/lark/lark_063.png' },
      { name: '064', code: '[lark:064]', url: '/emojis/lark/lark_064.png' },
      { name: '065', code: '[lark:065]', url: '/emojis/lark/lark_065.png' },
      { name: '066', code: '[lark:066]', url: '/emojis/lark/lark_066.png' },
      { name: '067', code: '[lark:067]', url: '/emojis/lark/lark_067.png' },
      { name: '068', code: '[lark:068]', url: '/emojis/lark/lark_068.png' },
      { name: '069', code: '[lark:069]', url: '/emojis/lark/lark_069.png' },
      { name: '070', code: '[lark:070]', url: '/emojis/lark/lark_070.png' },
      { name: '071', code: '[lark:071]', url: '/emojis/lark/lark_071.png' },
      { name: '072', code: '[lark:072]', url: '/emojis/lark/lark_072.png' },
      { name: '073', code: '[lark:073]', url: '/emojis/lark/lark_073.png' },
      { name: '074', code: '[lark:074]', url: '/emojis/lark/lark_074.png' },
      { name: '075', code: '[lark:075]', url: '/emojis/lark/lark_075.png' },
      { name: '076', code: '[lark:076]', url: '/emojis/lark/lark_076.png' },
      { name: '077', code: '[lark:077]', url: '/emojis/lark/lark_077.png' },
      { name: '078', code: '[lark:078]', url: '/emojis/lark/lark_078.png' },
      { name: '079', code: '[lark:079]', url: '/emojis/lark/lark_079.png' },
      { name: '080', code: '[lark:080]', url: '/emojis/lark/lark_080.png' },
      { name: '081', code: '[lark:081]', url: '/emojis/lark/lark_081.png' },
      { name: '082', code: '[lark:082]', url: '/emojis/lark/lark_082.png' },
      { name: '083', code: '[lark:083]', url: '/emojis/lark/lark_083.png' },
      { name: '084', code: '[lark:084]', url: '/emojis/lark/lark_084.png' },
      { name: '085', code: '[lark:085]', url: '/emojis/lark/lark_085.png' },
      { name: '086', code: '[lark:086]', url: '/emojis/lark/lark_086.png' },
      { name: '087', code: '[lark:087]', url: '/emojis/lark/lark_087.png' },
      { name: '088', code: '[lark:088]', url: '/emojis/lark/lark_088.png' },
      { name: '089', code: '[lark:089]', url: '/emojis/lark/lark_089.png' },
      { name: '090', code: '[lark:090]', url: '/emojis/lark/lark_090.png' },
      { name: '091', code: '[lark:091]', url: '/emojis/lark/lark_091.png' },
      { name: '092', code: '[lark:092]', url: '/emojis/lark/lark_092.png' },
      { name: '093', code: '[lark:093]', url: '/emojis/lark/lark_093.png' },
      { name: '094', code: '[lark:094]', url: '/emojis/lark/lark_094.png' },
      { name: '095', code: '[lark:095]', url: '/emojis/lark/lark_095.png' },
      { name: '096', code: '[lark:096]', url: '/emojis/lark/lark_096.png' },
      { name: '097', code: '[lark:097]', url: '/emojis/lark/lark_097.png' },
      { name: '098', code: '[lark:098]', url: '/emojis/lark/lark_098.png' },
      { name: '099', code: '[lark:099]', url: '/emojis/lark/lark_099.png' },
      { name: '100', code: '[lark:100]', url: '/emojis/lark/lark_100.png' },
      { name: '101', code: '[lark:101]', url: '/emojis/lark/lark_101.png' },
      { name: '102', code: '[lark:102]', url: '/emojis/lark/lark_102.png' },
      { name: '103', code: '[lark:103]', url: '/emojis/lark/lark_103.png' },
      { name: '104', code: '[lark:104]', url: '/emojis/lark/lark_104.png' },
      { name: '105', code: '[lark:105]', url: '/emojis/lark/lark_105.png' },
      { name: '106', code: '[lark:106]', url: '/emojis/lark/lark_106.png' },
      { name: '107', code: '[lark:107]', url: '/emojis/lark/lark_107.png' },
      { name: '108', code: '[lark:108]', url: '/emojis/lark/lark_108.png' },
      { name: '109', code: '[lark:109]', url: '/emojis/lark/lark_109.png' },
      { name: '110', code: '[lark:110]', url: '/emojis/lark/lark_110.png' },
      { name: '111', code: '[lark:111]', url: '/emojis/lark/lark_111.png' },
      { name: '112', code: '[lark:112]', url: '/emojis/lark/lark_112.png' },
      { name: '113', code: '[lark:113]', url: '/emojis/lark/lark_113.png' },
      { name: '114', code: '[lark:114]', url: '/emojis/lark/lark_114.png' },
      { name: '115', code: '[lark:115]', url: '/emojis/lark/lark_115.png' },
      { name: '116', code: '[lark:116]', url: '/emojis/lark/lark_116.png' },
      { name: '117', code: '[lark:117]', url: '/emojis/lark/lark_117.png' },
      { name: '118', code: '[lark:118]', url: '/emojis/lark/lark_118.png' },
      { name: '119', code: '[lark:119]', url: '/emojis/lark/lark_119.png' },
      { name: '120', code: '[lark:120]', url: '/emojis/lark/lark_120.png' },
      { name: '121', code: '[lark:121]', url: '/emojis/lark/lark_121.png' },
      { name: '122', code: '[lark:122]', url: '/emojis/lark/lark_122.png' },
      { name: '123', code: '[lark:123]', url: '/emojis/lark/lark_123.png' },
      { name: '124', code: '[lark:124]', url: '/emojis/lark/lark_124.png' },
      { name: '125', code: '[lark:125]', url: '/emojis/lark/lark_125.png' },
      { name: '126', code: '[lark:126]', url: '/emojis/lark/lark_126.png' },
      { name: '127', code: '[lark:127]', url: '/emojis/lark/lark_127.png' },
      { name: '128', code: '[lark:128]', url: '/emojis/lark/lark_128.png' },
      { name: '129', code: '[lark:129]', url: '/emojis/lark/lark_129.png' },
      { name: '130', code: '[lark:130]', url: '/emojis/lark/lark_130.png' },
      { name: '131', code: '[lark:131]', url: '/emojis/lark/lark_131.png' },
      { name: '132', code: '[lark:132]', url: '/emojis/lark/lark_132.png' },
      { name: '133', code: '[lark:133]', url: '/emojis/lark/lark_133.png' },
      { name: '134', code: '[lark:134]', url: '/emojis/lark/lark_134.png' },
      { name: '135', code: '[lark:135]', url: '/emojis/lark/lark_135.png' },
      { name: '136', code: '[lark:136]', url: '/emojis/lark/lark_136.png' },
      { name: '137', code: '[lark:137]', url: '/emojis/lark/lark_137.png' },
      { name: '138', code: '[lark:138]', url: '/emojis/lark/lark_138.png' },
      { name: '139', code: '[lark:139]', url: '/emojis/lark/lark_139.png' },
      { name: '140', code: '[lark:140]', url: '/emojis/lark/lark_140.png' },
      { name: '141', code: '[lark:141]', url: '/emojis/lark/lark_141.png' },
      { name: '142', code: '[lark:142]', url: '/emojis/lark/lark_142.png' },
      { name: '143', code: '[lark:143]', url: '/emojis/lark/lark_143.png' },
      { name: '144', code: '[lark:144]', url: '/emojis/lark/lark_144.png' },
      { name: '145', code: '[lark:145]', url: '/emojis/lark/lark_145.png' },
      { name: '146', code: '[lark:146]', url: '/emojis/lark/lark_146.png' },
      { name: '147', code: '[lark:147]', url: '/emojis/lark/lark_147.png' },
      { name: '148', code: '[lark:148]', url: '/emojis/lark/lark_148.png' },
      { name: '149', code: '[lark:149]', url: '/emojis/lark/lark_149.png' },
      { name: '150', code: '[lark:150]', url: '/emojis/lark/lark_150.png' },
      { name: '151', code: '[lark:151]', url: '/emojis/lark/lark_151.png' },
      { name: '152', code: '[lark:152]', url: '/emojis/lark/lark_152.png' },
      { name: '153', code: '[lark:153]', url: '/emojis/lark/lark_153.png' },
      { name: '154', code: '[lark:154]', url: '/emojis/lark/lark_154.png' },
      { name: '155', code: '[lark:155]', url: '/emojis/lark/lark_155.png' },
      { name: '156', code: '[lark:156]', url: '/emojis/lark/lark_156.png' },
      { name: '157', code: '[lark:157]', url: '/emojis/lark/lark_157.png' },
      { name: '158', code: '[lark:158]', url: '/emojis/lark/lark_158.png' },
      { name: '159', code: '[lark:159]', url: '/emojis/lark/lark_159.png' },
      { name: '160', code: '[lark:160]', url: '/emojis/lark/lark_160.png' },
      { name: '161', code: '[lark:161]', url: '/emojis/lark/lark_161.png' },
      { name: '162', code: '[lark:162]', url: '/emojis/lark/lark_162.png' },
      { name: '163', code: '[lark:163]', url: '/emojis/lark/lark_163.png' },
      { name: '164', code: '[lark:164]', url: '/emojis/lark/lark_164.png' },
      { name: '165', code: '[lark:165]', url: '/emojis/lark/lark_165.png' },
      { name: '166', code: '[lark:166]', url: '/emojis/lark/lark_166.png' },
      { name: '167', code: '[lark:167]', url: '/emojis/lark/lark_167.png' },
      { name: '168', code: '[lark:168]', url: '/emojis/lark/lark_168.png' },
      { name: '169', code: '[lark:169]', url: '/emojis/lark/lark_169.png' },
      { name: '170', code: '[lark:170]', url: '/emojis/lark/lark_170.png' },
      { name: '171', code: '[lark:171]', url: '/emojis/lark/lark_171.png' },
      { name: '172', code: '[lark:172]', url: '/emojis/lark/lark_172.png' },
      { name: '173', code: '[lark:173]', url: '/emojis/lark/lark_173.png' },
      { name: '174', code: '[lark:174]', url: '/emojis/lark/lark_174.png' },
      { name: '175', code: '[lark:175]', url: '/emojis/lark/lark_175.png' },
      { name: '176', code: '[lark:176]', url: '/emojis/lark/lark_176.png' },
      { name: '177', code: '[lark:177]', url: '/emojis/lark/lark_177.png' },
      { name: '178', code: '[lark:178]', url: '/emojis/lark/lark_178.png' },
      { name: '179', code: '[lark:179]', url: '/emojis/lark/lark_179.png' },
      { name: '180', code: '[lark:180]', url: '/emojis/lark/lark_180.png' },
      { name: '181', code: '[lark:181]', url: '/emojis/lark/lark_181.png' },
      { name: '182', code: '[lark:182]', url: '/emojis/lark/lark_182.png' },
      { name: '183', code: '[lark:183]', url: '/emojis/lark/lark_183.png' },
      { name: '184', code: '[lark:184]', url: '/emojis/lark/lark_184.png' },
      { name: '185', code: '[lark:185]', url: '/emojis/lark/lark_185.png' },
      { name: '186', code: '[lark:186]', url: '/emojis/lark/lark_186.png' },
      { name: '187', code: '[lark:187]', url: '/emojis/lark/lark_187.png' },
      { name: '188', code: '[lark:188]', url: '/emojis/lark/lark_188.png' },
      { name: '189', code: '[lark:189]', url: '/emojis/lark/lark_189.png' },
      { name: '190', code: '[lark:190]', url: '/emojis/lark/lark_190.png' },
      { name: '191', code: '[lark:191]', url: '/emojis/lark/lark_191.png' },
      { name: '192', code: '[lark:192]', url: '/emojis/lark/lark_192.png' },
      { name: '193', code: '[lark:193]', url: '/emojis/lark/lark_193.png' },
      { name: '194', code: '[lark:194]', url: '/emojis/lark/lark_194.png' },
      { name: '195', code: '[lark:195]', url: '/emojis/lark/lark_195.png' },
      { name: '196', code: '[lark:196]', url: '/emojis/lark/lark_196.png' },
      { name: '197', code: '[lark:197]', url: '/emojis/lark/lark_197.png' },
      { name: '198', code: '[lark:198]', url: '/emojis/lark/lark_198.png' },
      { name: '199', code: '[lark:199]', url: '/emojis/lark/lark_199.png' },
    ]
  },
  {
    key: 'xiaohongshu',
    name: '红薯',
    emojis: [
      { name: 'doge', code: '[xiaohongshu:doge]', url: '/emojis/xiaohongshu/xhs_doge.png' },
      { name: '买爆R', code: '[xiaohongshu:买爆R]', url: '/emojis/xiaohongshu/xhs_买爆R.png' },
      { name: '偷笑R', code: '[xiaohongshu:偷笑R]', url: '/emojis/xiaohongshu/xhs_偷笑R.png' },
      { name: '再见R', code: '[xiaohongshu:再见R]', url: '/emojis/xiaohongshu/xhs_再见R.png' },
      { name: '可怜R', code: '[xiaohongshu:可怜R]', url: '/emojis/xiaohongshu/xhs_可怜R.png' },
      { name: '叹气R', code: '[xiaohongshu:叹气R]', url: '/emojis/xiaohongshu/xhs_叹气R.png' },
      { name: '吃瓜R', code: '[xiaohongshu:吃瓜R]', url: '/emojis/xiaohongshu/xhs_吃瓜R.png' },
      { name: '吐舌头H', code: '[xiaohongshu:吐舌头H]', url: '/emojis/xiaohongshu/xhs_吐舌头H.png' },
      { name: '吧唧R', code: '[xiaohongshu:吧唧R]', url: '/emojis/xiaohongshu/xhs_吧唧R.png' },
      { name: '哇R', code: '[xiaohongshu:哇R]', url: '/emojis/xiaohongshu/xhs_哇R.png' },
      { name: '哭惹R', code: '[xiaohongshu:哭惹R]', url: '/emojis/xiaohongshu/xhs_哭惹R.png' },
      { name: '喝奶茶R', code: '[xiaohongshu:喝奶茶R]', url: '/emojis/xiaohongshu/xhs_喝奶茶R.png' },
      { name: '大笑R', code: '[xiaohongshu:大笑R]', url: '/emojis/xiaohongshu/xhs_大笑R.png' },
      { name: '失望R', code: '[xiaohongshu:失望R]', url: '/emojis/xiaohongshu/xhs_失望R.png' },
      { name: '害羞R', code: '[xiaohongshu:害羞R]', url: '/emojis/xiaohongshu/xhs_害羞R.png' },
      { name: '得意R', code: '[xiaohongshu:得意R]', url: '/emojis/xiaohongshu/xhs_得意R.png' },
      { name: '微笑R', code: '[xiaohongshu:微笑R]', url: '/emojis/xiaohongshu/xhs_微笑R.png' },
      { name: '惊恐R', code: '[xiaohongshu:惊恐R]', url: '/emojis/xiaohongshu/xhs_惊恐R.png' },
      { name: '扯脸H', code: '[xiaohongshu:扯脸H]', url: '/emojis/xiaohongshu/xhs_扯脸H.png' },
      { name: '扶墙R', code: '[xiaohongshu:扶墙R]', url: '/emojis/xiaohongshu/xhs_扶墙R.png' },
      { name: '抓狂R', code: '[xiaohongshu:抓狂R]', url: '/emojis/xiaohongshu/xhs_抓狂R.png' },
      { name: '抠鼻R', code: '[xiaohongshu:抠鼻R]', url: '/emojis/xiaohongshu/xhs_抠鼻R.png' },
      { name: '捂脸R', code: '[xiaohongshu:捂脸R]', url: '/emojis/xiaohongshu/xhs_捂脸R.png' },
      { name: '斜眼R', code: '[xiaohongshu:斜眼R]', url: '/emojis/xiaohongshu/xhs_斜眼R.png' },
      { name: '暗中观察R', code: '[xiaohongshu:暗中观察R]', url: '/emojis/xiaohongshu/xhs_暗中观察R.png' },
      { name: '汗颜R', code: '[xiaohongshu:汗颜R]', url: '/emojis/xiaohongshu/xhs_汗颜R.png' },
      { name: '派对R', code: '[xiaohongshu:派对R]', url: '/emojis/xiaohongshu/xhs_派对R.png' },
      { name: '生气R', code: '[xiaohongshu:生气R]', url: '/emojis/xiaohongshu/xhs_生气R.png' },
      { name: '皱眉R', code: '[xiaohongshu:皱眉R]', url: '/emojis/xiaohongshu/xhs_皱眉R.png' },
      { name: '睡觉R', code: '[xiaohongshu:睡觉R]', url: '/emojis/xiaohongshu/xhs_睡觉R.png' },
      { name: '石化R', code: '[xiaohongshu:石化R]', url: '/emojis/xiaohongshu/xhs_石化R.png' },
      { name: '笑哭R', code: '[xiaohongshu:笑哭R]', url: '/emojis/xiaohongshu/xhs_笑哭R.png' },
      { name: '自拍R', code: '[xiaohongshu:自拍R]', url: '/emojis/xiaohongshu/xhs_自拍R.png' },
      { name: '色色R', code: '[xiaohongshu:色色R]', url: '/emojis/xiaohongshu/xhs_色色R.png' },
      { name: '萌萌哒R', code: '[xiaohongshu:萌萌哒R]', url: '/emojis/xiaohongshu/xhs_萌萌哒R.png' },
      { name: '赞R', code: '[xiaohongshu:赞R]', url: '/emojis/xiaohongshu/xhs_赞R.png' },
      { name: '蹲后续H', code: '[xiaohongshu:蹲后续H]', url: '/emojis/xiaohongshu/xhs_蹲后续H.webp' },
      { name: '鄙视R', code: '[xiaohongshu:鄙视R]', url: '/emojis/xiaohongshu/xhs_鄙视R.png' },
      { name: '飞吻R', code: '[xiaohongshu:飞吻R]', url: '/emojis/xiaohongshu/xhs_飞吻R.png' },
      { name: '黄金薯R', code: '[xiaohongshu:黄金薯R]', url: '/emojis/xiaohongshu/xhs_黄金薯R.png' },
      { name: '黑薯问号R', code: '[xiaohongshu:黑薯问号R]', url: '/emojis/xiaohongshu/xhs_黑薯问号R.png' },
    ]
  },
]

export const emojiMap = new Map<string, EmojiItem>(
  emojiGroups.flatMap(group => group.emojis.map(emoji => [emoji.code, emoji]))
)

const emojiCodePattern = /\[[a-z0-9_-]+:[^\[\]\n]{1,32}\]/gi

export interface EmojiTextSegment {
  type: 'text' | 'emoji'
  value: string
  emoji?: EmojiItem
}

export function parseEmojiText(text = ''): EmojiTextSegment[] {
  const segments: EmojiTextSegment[] = []
  let lastIndex = 0

  for (const match of text.matchAll(emojiCodePattern)) {
    const code = match[0]
    const index = match.index ?? 0
    const emoji = emojiMap.get(code)

    if (!emoji) continue

    if (index > lastIndex) {
      segments.push({ type: 'text', value: text.slice(lastIndex, index) })
    }

    segments.push({ type: 'emoji', value: code, emoji })
    lastIndex = index + code.length
  }

  if (lastIndex < text.length) {
    segments.push({ type: 'text', value: text.slice(lastIndex) })
  }

  return segments.length ? segments : [{ type: 'text', value: text }]
}
