CREATE TABLE `user_sessions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `device_fingerprint` VARCHAR(64) NULL,
  `brand` VARCHAR(64) NULL,
  `model` VARCHAR(128) NULL,
  `platform` VARCHAR(64) NULL,
  `app_version` VARCHAR(64) NULL,
  `access_jti` VARCHAR(64) NOT NULL,
  `refresh_jti` VARCHAR(64) NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'active',
  `access_expires_at` TIMESTAMP(0) NOT NULL,
  `refresh_expires_at` TIMESTAMP(0) NOT NULL,
  `last_active_at` TIMESTAMP(0) NULL,
  `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_sessions_session_id_key` (`session_id`),
  INDEX `idx_user_status` (`user_id`, `status`),
  INDEX `idx_refresh_jti` (`refresh_jti`),
  INDEX `idx_session_status` (`session_id`, `status`),
  CONSTRAINT `user_sessions_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
